### ISSUE TITLE
ReferenceError: nil is not defined

### ISSUE THREAD

**Issue by yujinakayama** [Kev/clang-flags#1]
On opening C source file in atom-lint:

```
ReferenceError: nil is not defined
  at getFileContents (/Users/me/Projects/atom-lint/node_modules/clang-flags/lib/clang-flags.js:48:12)
  at getClangFlagsCompDB (/Users/me/Projects/atom-lint/node_modules/clang-flags/lib/clang-flags.js:53:22)
  at Object.module.exports.getClangFlags (/Users/me/Projects/atom-lint/node_modules/clang-flags/lib/clang-flags.js:14:15)
  at Clang.module.exports.Clang.buildCommand (/Users/me/Projects/atom-lint/lib/linter/clang.coffee:90:35)
  at Clang.module.exports.Clang.runClang (/Users/me/Projects/atom-lint/lib/linter/clang.coffee:31:33)
  at Clang.module.exports.Clang.run (/Users/me/Projects/atom-lint/lib/linter/clang.coffee:24:6)
  at LintRunner.module.exports.LintRunner.lint (/Users/me/Projects/atom-lint/lib/lint-runner.coffee:78:12)
  at LintRunner.module.exports.LintRunner.activate (/Users/me/Projects/atom-lint/lib/lint-runner.coffee:59:6)
  at LintRunner.module.exports.LintRunner.switchLinter (/Users/me/Projects/atom-lint/lib/lint-runner.coffee:48:6)
  at LintRunner.module.exports.LintRunner.startWatching (/Users/me/Projects/atom-lint/lib/lint-runner.coffee:20:6)
  at LintView.module.exports.LintView.initialize (/Users/me/Projects/atom-lint/lib/lint-view.coffee:26:17)
  at LintView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:137:25)
  at new LintView (/Users/me/Projects/atom-lint/lib/lint-view.coffee:11:3)
  at Object.module.exports.injectLintViewIntoEditorView (/Users/me/Projects/atom-lint/lib/atom-lint.coffee:69:20)
  at /Users/me/Projects/atom-lint/lib/atom-lint.coffee:29:8
  at HTMLDivElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/workspace-view.js:506:18)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)
  at Object.jQuery.event.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4594:12)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5119:17)
  at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at ReactEditorView.jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at ReactEditorView.jQuery.fn.extend.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5118:15)
  at ReactEditorView.module.exports.ReactEditorView.afterAttach (/Applications/Atom.app/Contents/Resources/app/src/react-editor-view.js:156:19)
  at callAttachHook (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:333:107)
  at [object Object].jQuery.fn.(anonymous function) [as append] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:349:9)
  at PaneView.module.exports.PaneView.onActiveItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-view.js:298:24)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-view.js:3:61
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
  at Pane.module.exports.Model.set (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:166:21)
  at Pane.accessor.set (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:57:23)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:186:25)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:171:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:252:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:349:11)
```

``` bash
$ grep version /Users/me/Projects/atom-lint/node_modules/clang-flags/package.json
  "version": "0.1.2",
```

**Comment by Kev** [comment]
Thanks. This isn't happening for me - are you able to share a minimal C file example it happens with, and do you have a .clang_complete file?

**Comment by JMLX42** [comment]
Here is how I fixed it in the javascript:

```
// Generated by CoffeeScript 1.7.1
(function() {
  var Directory, File, getClangFlagsCompDB, getClangFlagsDotClangComplete, getFileContents, path, readFileSync, _ref;

  path = require('path');

  readFileSync = require('fs').readFileSync;

  _ref = require('pathwatcher'), File = _ref.File, Directory = _ref.Directory;

  module.exports = {
    getClangFlags: function(fileName) {
      var flags;
      flags = getClangFlagsCompDB(fileName);
      if (!flags) {
        return getClangFlagsDotClangComplete(fileName);
      }
      return flags;
    },
    activate: function(state) {}
  };

  getFileContents = function(startFile, fileName) {
    var args, contents, error, searchDir, searchFile, searchFilePath, thisDir;
    searchDir = path.dirname(startFile);
    args = [];
    while (searchDir.length) {
      searchFilePath = path.join(searchDir, fileName);
      searchFile = new File(searchFilePath);
      if (searchFile.exists()) {
        contents = "";
        try {
          contents = readFileSync(searchFilePath, 'utf8');
          return [searchDir, contents];
        } catch (_error) {
          error = _error;
          console.log("clang-flags for " + fileName + " couldn't read file " + searchFilePath);
          console.log(error);
        }
        return nil;
      }
      thisDir = new Directory(searchDir);
      if (thisDir.isRoot()) {
        break;
      }
      searchDir = thisDir.getParent().getPath();
    }
    return nil;
  };

  getClangFlagsCompDB = function(fileName) {
    var args, compDB, compDBContents;
    try {
        compDBContents = getFileContents(fileName, "compile_commands.json");
    } catch (_error) {
        return 0;
    }
    args = 0;
    if (compDBContents && compDBContents[1].length > 0) {
      compDB = JSON.parse(compDBContents[1]);
    }
    return args;
  };

  getClangFlagsDotClangComplete = function(fileName) {
    var args, clangCompleteContents;
    clangCompleteContents = getFileContents(fileName, ".clang_complete");
    args = [];
    if (clangCompleteContents && clangCompleteContents[1].length > 0) {
      args = clangCompleteContents[1].split("\n");
      args = args.concat(["-working-directory=" + clangCompleteContents[0]]);
    }
    return args;
  };

}).call(this);
```

1- The getClangFlags handling of the flags value was wrong
2- getClangFlagsDotClangComplete used an undefined searchPath variable, I made sure getFileContents returns both the content AND the found searchDir in an array
3- getClangFlagsCompDB would simply crash if the file compile_commands.json did not exist, fixed it using a try catch

I'm no coffee script expert, maybe you could backport these fixes?
It also fixes this: https://github.com/yasuyuky/autocomplete-clang/issues/21

Regards,

**Comment by Kev** [comment]
I think this is resolved now, can you let me know if it's not, please?

**Comment by Kev** [comment]
Closing unless someone tells me this is still an issue.
